services:

  # 데이터베이스
  postgres:
    image: postgres:18
    container_name: postgres-palja
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: palja
      POSTGRES_USER: paljagood
      POSTGRES_PASSWORD: paljagood
      TZ: Asia/Seoul
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - msa-network

  # Redis
  redis:
    image: redis:7.2
    container_name: redis-palja
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - msa-network

  # Kafka & Zookeeper
  zookeeper:
    image: wurstmeister/zookeeper:latest
    platform: linux/amd64
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000tproej
    networks:
      - msa-network

  kafka:
    image: wurstmeister/kafka:latest
    platform: linux/amd64
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:29092,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - msa-network

  # Kafka UI (관리 페이지)
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    platform: linux/amd64
    ports:
      - "18080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      KAFKA_CLUSTERS_0_READONLY: "false"
    networks:
      - msa-network

  # Zipkin
  zipkin:
    image: openzipkin/zipkin:latest
    platform: linux/amd64
    ports:
      - "9411:9411"
    environment:
      STORAGE_TYPE: mem
    networks:
      - msa-network

# 볼륨
volumes:
  redis_data:

# 네트워크
networks:
  msa-network:
    driver: bridge